name: "Terraform DEV Deployment"

on:
  workflow_dispatch:   # manual trigger
  push:
    paths:
      - 'terraform/environments/dev/**'

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    name: "Terraform Plan & Apply - DEV"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5   # or latest stable version

    - name: Terraform Init
      working-directory: terraform/environments/dev
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform/environments/dev
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch'   # Only apply on manual trigger!
      working-directory: terraform/environments/dev
      run: terraform apply -auto-approve
