name: "Terraform QA Deployment"

on:
  workflow_dispatch:   # manual trigger
  push:
    paths:
      - 'terraform/environments/qa/**'

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    name: "Terraform Plan and Apply - QA"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      working-directory: terraform/environments/qa
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform/environments/qa
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch'
      working-directory: terraform/environments/qa
      run: terraform apply -auto-approve
